### ISSUE TITLE
more natural syntax

### ISSUE THREAD

**Issue by adamralph** [cryptic-mystic/WithFormat#1]
I like the idea of this library!

However, looking at the fluent methods in the example I can't help thinking the language could be a bit more natural, e.g.

``` c#
5.WithPercent().WithPrecision(3).Format();
5.WithCurrency().WithCulture<JapaneseJapanCulture>().Format();
```

would read better as:

``` c#
5.AsPercentage().WithPrecision(3).Format();
5.AsCurrency().Using<JapaneseJapanCulture>().Format();
```

i.e. closer to the natural language of:

> "format 5 as a percentage with a precision of 3"
> "format 5 as a currency using the Japanese in Japan culture"

Just throwing this out there as a thought.

**Comment by cryptic-mystic** [comment]
Whoa! Great! I seriously appreciate any feedback or suggestions, so
continue to shoot them my way!

I actually agree, I like your syntax a tad better. I'll do some refactoring
in an upcoming commit. Thanks again for the feedback :)

**Comment by cryptic-mystic** [comment]
Or feel free to send a pull request ;)

**Comment by adamralph** [comment]
Nice work!
